container:
  image: gcc:latest

make_task:
  prep_script: apt-get update; apt-get install -y libpam-google-authenticator libpam0g-dev
  compile_script: make
  install_script: make install

# I do not know why this is failing on CI
# (it works at home on several computers)
test_task:
  depends_on:
    - make
  test_script: yes | google-authenticator; echo; google-auth "`tail -1 ~/.google_authenticator`"

